### ISSUE TITLE
Was the pigpio error list taken from somewhere else?

### ISSUE THREAD

**Issue by janekb04** [CyberDuckProject/driver#2]
It looks like possibly the list of the error codes and messages was taken from [here](https://github.com/guymcswain/pigpio-client/wiki/pigpio-error-messages). If it was, then, maybe we should add a comment acknowledging that.

https://github.com/CyberDuckProject/driver/blob/0abf4716c6109efc1b7f8718a4ff5b6f9078c8c9/src/peripheral_error.cpp#L20

**Comment by adamsoltan** [comment]
Fixed in 0465cf2b46a2119a794fd21b3d4d19465c81f05c.
